### ISSUE TITLE
Documentation for end-to-end training on S&M model on TrecQA data

### ISSUE THREAD

**Issue by lintool** [castorini/Castor#1]
Data should go into this repo: https://github.com/lintool/Castor-data

Instructions should be at a sufficient level of detail that I can copy/paste into my shell and replicate some reasonable facsimile of the original model.

**Comment by gauravbaruah** [comment]
Can we close this issue? This issue of course might repeat for each model/dataset. If we are going to change the layout of the repo, then this shifts to the component that links everything together.

**Comment by lintool** [comment]
Closing.
