### ISSUE TITLE
Reimplement NCE on SM model

### ISSUE THREAD

**Issue by lintool** [castorini/Castor#10]
NCE = Noise Contrastive Estimation
http://dl.acm.org/citation.cfm?id=2983872

Use our SM model has the building block.

**Comment by lintool** [comment]
Assigning to @Victor0118 - might want to do NCE over MP-CNN instead of NCE over SM.

**Comment by Victor0118** [comment]
Yeah. I am starting porting NCE to SM first and then move to MP-CNN or Very Deep Pairwise Word Interaction Neural Networks hopefully.

**Comment by lintool** [comment]
Closing this issue. NCE needs to be refactored to fit into the current code base structure, but that's for another issue.
