### ISSUE TITLE
Reimplement Kim's sentence classification model

### ISSUE THREAD

**Issue by lintool** [castorini/Castor#12]
See https://arxiv.org/abs/1408.5882
Helpful post: http://www.wildml.com/2015/12/implementing-a-cnn-for-text-classification-in-tensorflow/

**Comment by HTAustin** [comment]
I just found there are some repo has reproduced this model:
https://github.com/Shawn1993/cnn-text-classification-pytorch

**Comment by lintool** [comment]
I also found this:
https://github.com/harvardnlp/sent-conv-torch

It's in (Cuda) Torch, but seems to be more complete.

**Comment by lintool** [comment]
@Impavidity should we close this issue?

**Comment by lintool** [comment]
Seems like @rosequ has verified the code as working. Closing issue.
