### ISSUE TITLE
SM model: backprop to word embeddings

### ISSUE THREAD

**Issue by lintool** [castorini/Castor#13]
According to https://arxiv.org/abs/1510.03820 and other places, "non-static" word-embeddings are a win. We should adapt our implementation of the SM model to do so.

**Comment by rosequ** [comment]
The existing SM model has non-static word embeddings. Any `Variable` is backproped unless one sets the `requires_grad`  property to `False`.
For example:
```python
self.static_question_embed = nn.Embedding(questions_num, words_dim)
self.static_question_embed.weight.requires_grad = False
```
Here, `static_question_embed` is static.
