### ISSUE TITLE
the codes of vdpwi is not work

### ISSUE THREAD

**Issue by xyx-x** [castorini/Castor#137]
I have followed the readme to setup the environment.  And I also export the PYTHONPATH of Castor in the castor virtual environment. When i use the tool of vdpwi, it exits the error("ModuleNotFoundError: No module named 'utils.relevancy_metrics'"). However, the other python file (for example: python files in the "common" directory ) can be imported successfully. I want to get some help.

**Comment by tuzhucheng** [comment]
Hi @xyx-x, please run the following from the main Castor directory (and NOT from inside vdpwi) and see if it works?

```
python -m vdpwi vdpwi.sick.model.castor --dataset sick --lr 5e-4 --optimizer rmsprop --epochs 15 --batch-size 8 --rnn-hidden-dim 256 --epsilon 1e-7
```

You should not need to set `PYTHONPATH`. Please let me know where you saw that instruction (legacy) so I can remove it.

**Comment by xyx-x** [comment]
thank you. It works. There is no instruction about setting PYTHONPATH. I met the error so i try to handle the problem with setting PYTHONPATH.
