### ISSUE TITLE
Import all datasets in Lan and Xu COLING paper

### ISSUE THREAD

**Issue by lintool** [castorini/castor#146]
Lan and Xu's COLING paper: http://aclweb.org/anthology/C18-1328

Explores a bunch of datasets - some of which we have in Castor already, some not. We should make sure we can run the same range of experiments as in their work.

@Victor0118 starting looking into this - @likicode can you please assist? This will feed into the VDPWI analyses that you're running.

**Comment by Victor0118** [comment]
This is done.
