### ISSUE TITLE
Rename sm_model to sm_cnn_model

### ISSUE THREAD

**Issue by lintool** [castorini/Castor#18]
Might want to rename sm_model to sm_cnn_model to be consistent with @Jeffyrao 's impl?
https://github.com/castorini/SM-CNN-Torch

**Comment by lintool** [comment]
Or even just `sm_cnn`?

**Comment by gauravbaruah** [comment]
@rosequ @salman1993 How might the renaming affect the anserini e2e connection? Are there any hardcoded statements that will need to be addressed for this change?

**Comment by lintool** [comment]
@gauravbaruah bumping this issue again. to be consistent with other models that we've merged in, should we rename to `sm_cnn`?

**Comment by rosequ** [comment]
This issue is resolved. Can we close it now?
