### ISSUE TITLE
High level-documentation on setting up dev environment

### ISSUE THREAD

**Issue by lintool** [castorini/Castor#4]
We need high-level documentation to make sure everyone's environment is sync'ed. For example:
+ Python 3.5 or 3.6?
+ What version of PyTorch to install
+ Basically installation instructions on different OS (Mac for me)
+ etc

**Comment by snapbug** [comment]
Using docker (or such) completely negates this issue, once the docker image is created.

**Comment by lintool** [comment]
@tuzhucheng has been working on this - part of merge https://github.com/castorini/Castor/commit/5bf33bf8ea4a163ee54799412209ae21c68c3c79
