### ISSUE TITLE
Kim CNN: Tokenizer

### ISSUE THREAD

**Issue by rosequ** [castorini/Castor#44]
Replace [this](https://github.com/castorini/Castor/blob/master/kim_cnn/etc/utils.py#L4) with the PTB tokenizer.

**Comment by daemon** [comment]
Where should I put stanford-postagger.jar (NLTK)?

**Comment by rosequ** [comment]
@daemon I was supposed to close this issue earlier since we found out that the datasets used by KimCNN (at least TREC and SST) are PTB tokenized. If we are going to extend KimCNN to other datasets, we would have to separately tokenize the text. I suggest we add a link in the README pointing to stanford-postagger.jar.
