### ISSUE TITLE
Run MP-CNN on various QA datasets

### ISSUE THREAD

**Issue by tuzhucheng** [castorini/Castor#55]
Add data loaders, trainer, and evaluator for training TrecQA data for MP-CNN per request from @Victor0118.

**Comment by Victor0118** [comment]
Thanks for you great help!

**Comment by Victor0118** [comment]
Hi, @tuzhucheng . I highly suggest you use this trec_eval script since it is provided by the TrecQA dataset and widely used. You just need to generate one gold.txt and one submission.txt and throw them to the black-box script. You can refer to SM-CNN which does the same work.

**Comment by tuzhucheng** [comment]
Sure, I'll just use the subprocess module to achieve this.

**Comment by lintool** [comment]
We want to look at TrecQA, wikiQA, InsuranceQA, and SQuAD.

**Comment by lintool** [comment]
Since @tuzhucheng just submitted his thesis on MP-CNN, we'll consider this issue closed!
