### ISSUE TITLE
Figure out why end-to-end QA system with SM model sucks

### ISSUE THREAD

**Issue by lintool** [castorini/Castor#8]
According to @rosequ the end-to-end QA system has lower accuracy than just using idf passage scorer. This makes no sense. We need to figure out why.

**Comment by gauravbaruah** [comment]
- The external overlap features used by the model are necessary for improved performance (~0.75 MAP).
- These overlap features were computed before training the model and were _normalized_ before saving to file. During training these saved normalized features were loaded in during model training.
- **Issue:** During deployment, even though we compute overlap feaures for candidate answers, we have no way of normalizing them, leading to bad scores from the model.
- **Workaround 1:** Completely ignore external features during training and deployment. --> lower performance than when using normalized features (~0.6 MAP)
- **Workaround 2:** Do not normalize external features. --> lower performance than Workaround 1 (~0.4 MAP).

**Comment by HTAustin** [comment]
Workaround 3: Normalize external features with TrecQA QA pairs features.

**Comment by lintool** [comment]
Let's implement **workaround 1**.

I'd like two conditions:
+ Anserini + `IdfPassageScorer`
+ Anserini + `IdfPassageScorer` + sm ranker

Please report e2e RBP numbers on TrecQA dev set.

**Comment by lintool** [comment]
Okay, we know the reason why now - it's an issue of feature normalization. Closing issue.
